name: Process Input Files


on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  process-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Get changed files in inputs folder
      id: changed-files
      uses: tj-actions/changed-files@v40
      with:
        files: inputs/**
        
    - name: Process changed files
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo "Processing changed files..."
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "Processing: $file"
          python bedrock.py "$file"
        done
      
    - name: Commit and push output files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add outputs/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update output files [skip ci]"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}